-- ============================================================
-- Zuma App — Seed Data
-- Mirrors data/mock.ts so the app looks identical after migration
-- ============================================================

-- Test user profile
insert into profiles (id, full_name, email)
values ('00000000-0000-0000-0000-000000000001', 'Nico Baldovino', 'nico@example.com')
on conflict (id) do nothing;

-- Ensure main bucket exists
select ensure_main_bucket('00000000-0000-0000-0000-000000000001');

-- Update main bucket to match mock data
update buckets
   set current_amount = 50000,
       icon = 'Wallet',
       color_key = 'neutral',
       sort_order = -1
 where user_id = '00000000-0000-0000-0000-000000000001' and is_main = true;

-- Savings buckets
insert into buckets (id, user_id, name, icon, icon_type, color_key, current_amount, target_amount, sort_order, created_at) values
  ('00000000-0000-0000-0000-b00000000007', '00000000-0000-0000-0000-000000000001', 'Tokyo Trip',              'Airplane',       'icon', 'gold',     180000,  500000,  0, '2025-07-01T00:00:00Z'),
  ('00000000-0000-0000-0000-b00000000002', '00000000-0000-0000-0000-000000000001', 'Nikon Camera Mirrorless', 'Camera',         'icon', 'orange',   250000, 1000000,  1, '2025-02-01T00:00:00Z'),
  ('00000000-0000-0000-0000-b00000000004', '00000000-0000-0000-0000-000000000001', 'Jordan 4 Retro',          'Sneaker',        'icon', 'coral',     18000,   25000,  2, '2025-04-10T00:00:00Z'),
  ('00000000-0000-0000-0000-b00000000008', '00000000-0000-0000-0000-000000000001', 'Birthday Gift',           'Gift',           'icon', 'rose',       5000,   15000,  3, '2025-08-20T00:00:00Z'),
  ('00000000-0000-0000-0000-b00000000003', '00000000-0000-0000-0000-000000000001', 'Cancun Vacation',         'Island',         'icon', 'lavender', 250000, 1000000,  4, '2025-03-01T00:00:00Z'),
  ('00000000-0000-0000-0000-b00000000005', '00000000-0000-0000-0000-000000000001', 'MacBook Pro M4',          'Laptop',         'icon', 'sky',      120000,  350000,  5, '2025-05-01T00:00:00Z'),
  ('00000000-0000-0000-0000-b00000000006', '00000000-0000-0000-0000-000000000001', 'PS5 Pro Bundle',          'GameController', 'icon', 'mint',      35000,   80000,  6, '2025-06-15T00:00:00Z'),
  ('00000000-0000-0000-0000-b00000000001', '00000000-0000-0000-0000-000000000001', 'Gibson Electric guitar',  'Guitar',         'icon', 'lime',     150000, 1000000,  7, '2025-01-15T00:00:00Z')
on conflict (id) do nothing;

-- Get the main bucket ID for transaction references
-- (it was auto-generated by ensure_main_bucket)

-- Transactions — bucket-1 (Gibson Electric guitar)
insert into transactions (user_id, bucket_id, type, amount, description, created_at) values
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-b00000000001', 'deposit',     100000, 'Funds added',             '2026-03-29T10:00:00Z'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-b00000000001', 'deposit',     100000, 'Funds added',             '2026-03-29T08:00:00Z'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-b00000000001', 'deposit',      50000, 'Funds added',             '2026-03-27T12:00:00Z'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-b00000000001', 'deposit',      75000, 'Funds added',             '2026-03-25T09:00:00Z'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-b00000000001', 'transfer_in',  25000, 'Moved from Main Balance', '2026-03-23T15:00:00Z'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-b00000000001', 'deposit',     100000, 'Funds added',             '2026-03-20T10:00:00Z'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-b00000000001', 'deposit',      50000, 'Funds added',             '2026-03-18T11:00:00Z'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-b00000000001', 'deposit',     100000, 'Funds added',             '2026-03-15T14:00:00Z'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-b00000000001', 'transfer_in',  50000, 'Moved from Main Balance', '2026-03-12T08:00:00Z'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-b00000000001', 'deposit',      80000, 'Funds added',             '2026-03-10T10:00:00Z'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-b00000000001', 'deposit',      60000, 'Funds added',             '2026-03-08T14:00:00Z'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-b00000000001', 'transfer_in',  30000, 'Moved from Main Balance', '2026-03-05T09:00:00Z'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-b00000000001', 'deposit',     120000, 'Funds added',             '2026-03-02T11:00:00Z'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-b00000000001', 'deposit',      45000, 'Funds added',             '2026-02-28T16:00:00Z'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-b00000000001', 'deposit',      90000, 'Funds added',             '2026-02-25T08:00:00Z');

-- Transactions — bucket-2 (Nikon Camera)
insert into transactions (user_id, bucket_id, type, amount, description, created_at) values
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-b00000000002', 'deposit', 150000, 'Funds added', '2026-03-28T14:00:00Z'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-b00000000002', 'deposit', 100000, 'Funds added', '2026-03-27T09:00:00Z');

-- Transactions — bucket-3 (Cancun Vacation)
insert into transactions (user_id, bucket_id, type, amount, description, created_at) values
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-b00000000003', 'deposit',     200000, 'Funds added',             '2026-03-28T12:00:00Z'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-b00000000003', 'transfer_in',  50000, 'Moved from Main Balance', '2026-03-26T16:00:00Z');

-- Transactions — wallet-level deposit (null bucket_id)
insert into transactions (user_id, bucket_id, type, amount, description, created_at) values
  ('00000000-0000-0000-0000-000000000001', null, 'deposit', 500000, 'Bank deposit', '2026-03-25T10:00:00Z');

-- Transactions — bucket-4 (Jordan 4 Retro)
insert into transactions (user_id, bucket_id, type, amount, description, created_at) values
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-b00000000004', 'deposit', 10000, 'Funds added', '2026-03-28T10:00:00Z'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-b00000000004', 'deposit',  8000, 'Funds added', '2026-03-20T14:00:00Z');

-- Transactions — bucket-5 (MacBook Pro M4)
insert into transactions (user_id, bucket_id, type, amount, description, created_at) values
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-b00000000005', 'deposit', 50000, 'Funds added', '2026-03-27T09:00:00Z'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-b00000000005', 'deposit', 70000, 'Funds added', '2026-03-15T11:00:00Z');

-- Transactions — bucket-6 (PS5 Pro Bundle)
insert into transactions (user_id, bucket_id, type, amount, description, created_at) values
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-b00000000006', 'deposit',     20000, 'Funds added',             '2026-03-26T16:00:00Z'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-b00000000006', 'transfer_in', 15000, 'Moved from Main Balance', '2026-03-18T08:00:00Z');

-- Transactions — bucket-7 (Tokyo Trip)
insert into transactions (user_id, bucket_id, type, amount, description, created_at) values
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-b00000000007', 'deposit', 100000, 'Funds added', '2026-03-25T10:00:00Z'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-b00000000007', 'deposit',  80000, 'Funds added', '2026-03-10T12:00:00Z');

-- Transactions — bucket-8 (Birthday Gift)
insert into transactions (user_id, bucket_id, type, amount, description, created_at) values
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-b00000000008', 'deposit', 5000, 'Funds added', '2026-03-29T15:00:00Z');

-- Default notification preferences
insert into notification_preferences (user_id)
values ('00000000-0000-0000-0000-000000000001')
on conflict (user_id) do nothing;
