import type { ComponentType } from 'react';
import type { IconProps } from 'phosphor-react-native';
import {
  Airplane, Baby, Backpack, Bag, Balloon, Bank, Barbell, Baseball, Basketball,
  Bathtub, Bed, Bicycle, Bird, Boat, Book, Bone, Bread, Briefcase,
  Building, Bus, Cactus, Cake, Camera, Campfire, Car, Cat, Certificate, Compass,
  Chair, Coin, Coffee, Confetti, Cookie, CookingPot, Couch, CreditCard,
  Crown, Desk, Diamond, Dog, Dress, Egg, Eye, Fan, Fire, Fish, Flag,
  Flashlight, Flower, Football, ForkKnife, GameController, Garage,
  GasPump, Gift, GlobeSimple, Golf, GraduationCap, Guitar, Hamburger,
  Hammer, HandCoins, Headphones, Heart, Horse, House, IceCream, Island, Microphone,
  Jeep, Joystick, Key, Knife, Lamp, Laptop, Leaf, Lifebuoy, Lighthouse,
  Lock, Medal, Megaphone, Money, Motorcycle, Mountains, Needle, Orange,
  PaintBucket, Palette, PaperPlane, Park, PawPrint, PenNib, Pencil, Phone,
  PiggyBank, Pizza, Plant, Popcorn, Racquet, Receipt, Rocket, Sailboat,
  Scissors, ShieldCheck, ShoppingBag, ShoppingCart, Skull, Sneaker,
  Snowflake, Sparkle, Star, Stethoscope, Storefront, Suitcase, Sun,
  Sunglasses, Sword, Taxi, TennisBall, Tent, ThumbsUp, Tooth, Train,
  Tree, Trophy, Truck, Umbrella, Van, VideoCamera, Wallet, Wine, Wrench,
} from 'phosphor-react-native';

type IconEntry = {
  name: string;
  component: ComponentType<IconProps>;
};

export const BUCKET_ICON_LIST: IconEntry[] = [
  { name: 'Airplane', component: Airplane },
  { name: 'Baby', component: Baby },
  { name: 'Backpack', component: Backpack },
  { name: 'Bag', component: Bag },
  { name: 'Balloon', component: Balloon },
  { name: 'Bank', component: Bank },
  { name: 'Barbell', component: Barbell },
  { name: 'Baseball', component: Baseball },
  { name: 'Basketball', component: Basketball },
  { name: 'Bathtub', component: Bathtub },
  { name: 'Bed', component: Bed },
  { name: 'Bicycle', component: Bicycle },
  { name: 'Bird', component: Bird },
  { name: 'Boat', component: Boat },
  { name: 'Book', component: Book },
  { name: 'Bone', component: Bone },
  { name: 'Bread', component: Bread },
  { name: 'Briefcase', component: Briefcase },
  { name: 'Building', component: Building },
  { name: 'Bus', component: Bus },
  { name: 'Cactus', component: Cactus },
  { name: 'Cake', component: Cake },
  { name: 'Camera', component: Camera },
  { name: 'Campfire', component: Campfire },
  { name: 'Car', component: Car },
  { name: 'Cat', component: Cat },
  { name: 'Certificate', component: Certificate },
  { name: 'Chair', component: Chair },
  { name: 'Compass', component: Compass },
  { name: 'Coin', component: Coin },
  { name: 'Coffee', component: Coffee },
  { name: 'Confetti', component: Confetti },
  { name: 'Cookie', component: Cookie },
  { name: 'CookingPot', component: CookingPot },
  { name: 'Couch', component: Couch },
  { name: 'CreditCard', component: CreditCard },
  { name: 'Crown', component: Crown },
  { name: 'Desk', component: Desk },
  { name: 'Diamond', component: Diamond },
  { name: 'Dog', component: Dog },
  { name: 'Dress', component: Dress },
  { name: 'Egg', component: Egg },
  { name: 'Eye', component: Eye },
  { name: 'Fan', component: Fan },
  { name: 'Fire', component: Fire },
  { name: 'Fish', component: Fish },
  { name: 'Flag', component: Flag },
  { name: 'Flashlight', component: Flashlight },
  { name: 'Flower', component: Flower },
  { name: 'Football', component: Football },
  { name: 'ForkKnife', component: ForkKnife },
  { name: 'GameController', component: GameController },
  { name: 'Garage', component: Garage },
  { name: 'GasPump', component: GasPump },
  { name: 'Gift', component: Gift },
  { name: 'GlobeSimple', component: GlobeSimple },
  { name: 'Golf', component: Golf },
  { name: 'GraduationCap', component: GraduationCap },
  { name: 'Guitar', component: Guitar },
  { name: 'Hamburger', component: Hamburger },
  { name: 'Hammer', component: Hammer },
  { name: 'HandCoins', component: HandCoins },
  { name: 'Headphones', component: Headphones },
  { name: 'Heart', component: Heart },
  { name: 'Horse', component: Horse },
  { name: 'House', component: House },
  { name: 'IceCream', component: IceCream },
  { name: 'Island', component: Island },
  { name: 'Microphone', component: Microphone },
  { name: 'Jeep', component: Jeep },
  { name: 'Joystick', component: Joystick },
  { name: 'Key', component: Key },
  { name: 'Knife', component: Knife },
  { name: 'Lamp', component: Lamp },
  { name: 'Laptop', component: Laptop },
  { name: 'Leaf', component: Leaf },
  { name: 'Lifebuoy', component: Lifebuoy },
  { name: 'Lighthouse', component: Lighthouse },
  { name: 'Lock', component: Lock },
  { name: 'Medal', component: Medal },
  { name: 'Megaphone', component: Megaphone },
  { name: 'Money', component: Money },
  { name: 'Motorcycle', component: Motorcycle },
  { name: 'Mountains', component: Mountains },
  { name: 'Needle', component: Needle },
  { name: 'Orange', component: Orange },
  { name: 'PaintBucket', component: PaintBucket },
  { name: 'Palette', component: Palette },
  { name: 'PaperPlane', component: PaperPlane },
  { name: 'Park', component: Park },
  { name: 'PawPrint', component: PawPrint },
  { name: 'PenNib', component: PenNib },
  { name: 'Pencil', component: Pencil },
  { name: 'Phone', component: Phone },
  { name: 'PiggyBank', component: PiggyBank },
  { name: 'Pizza', component: Pizza },
  { name: 'Plant', component: Plant },
  { name: 'Popcorn', component: Popcorn },
  { name: 'Racquet', component: Racquet },
  { name: 'Receipt', component: Receipt },
  { name: 'Rocket', component: Rocket },
  { name: 'Sailboat', component: Sailboat },
  { name: 'Scissors', component: Scissors },
  { name: 'ShieldCheck', component: ShieldCheck },
  { name: 'ShoppingBag', component: ShoppingBag },
  { name: 'ShoppingCart', component: ShoppingCart },
  { name: 'Skull', component: Skull },
  { name: 'Sneaker', component: Sneaker },
  { name: 'Snowflake', component: Snowflake },
  { name: 'Sparkle', component: Sparkle },
  { name: 'Star', component: Star },
  { name: 'Stethoscope', component: Stethoscope },
  { name: 'Storefront', component: Storefront },
  { name: 'Suitcase', component: Suitcase },
  { name: 'Sun', component: Sun },
  { name: 'Sunglasses', component: Sunglasses },
  { name: 'Sword', component: Sword },
  { name: 'Taxi', component: Taxi },
  { name: 'TennisBall', component: TennisBall },
  { name: 'Tent', component: Tent },
  { name: 'ThumbsUp', component: ThumbsUp },
  { name: 'Tooth', component: Tooth },
  { name: 'Train', component: Train },
  { name: 'Tree', component: Tree },
  { name: 'Trophy', component: Trophy },
  { name: 'Truck', component: Truck },
  { name: 'Umbrella', component: Umbrella },
  { name: 'Van', component: Van },
  { name: 'VideoCamera', component: VideoCamera },
  { name: 'Wallet', component: Wallet },
  { name: 'Wine', component: Wine },
  { name: 'Wrench', component: Wrench },
];

const iconMap: Record<string, ComponentType<IconProps>> = {};
for (const entry of BUCKET_ICON_LIST) {
  iconMap[entry.name] = entry.component;
}

const fallback = Star;

export function getBucketIcon(name: string): ComponentType<IconProps> {
  return iconMap[name] ?? fallback;
}
