type EmojiEntry = {
  emoji: string;
  tags: string;
};

export function getEmojiName(emoji: string): string {
  const entry = EMOJI_LIST.find((e) => e.emoji === emoji);
  if (!entry) return emoji;
  const first = entry.tags.split(' ')[0];
  return first.charAt(0).toUpperCase() + first.slice(1);
}

export const EMOJI_LIST: EmojiEntry[] = [
  // Travel
  { emoji: '✈️', tags: 'airplane travel flight' },
  { emoji: '🏖️', tags: 'beach vacation island' },
  { emoji: '🏔️', tags: 'mountain hiking nature' },
  { emoji: '🗺️', tags: 'map travel world' },
  { emoji: '🧳', tags: 'luggage travel suitcase' },
  { emoji: '⛺', tags: 'tent camping outdoor' },
  { emoji: '🚗', tags: 'car drive road' },
  { emoji: '🚲', tags: 'bicycle bike cycling' },
  { emoji: '🛳️', tags: 'cruise ship boat' },
  { emoji: '🚀', tags: 'rocket space launch' },
  { emoji: '🗼', tags: 'tower paris travel' },
  { emoji: '🌍', tags: 'globe world earth' },
  // Food & Drink
  { emoji: '☕', tags: 'coffee drink cafe' },
  { emoji: '🍕', tags: 'pizza food italian' },
  { emoji: '🍔', tags: 'burger food fast' },
  { emoji: '🍣', tags: 'sushi food japanese' },
  { emoji: '🍰', tags: 'cake dessert birthday' },
  { emoji: '🍷', tags: 'wine drink alcohol' },
  { emoji: '🍺', tags: 'beer drink bar' },
  { emoji: '🥑', tags: 'avocado food healthy' },
  { emoji: '🍩', tags: 'donut dessert sweet' },
  { emoji: '🧁', tags: 'cupcake dessert sweet' },
  // Shopping
  { emoji: '👟', tags: 'sneaker shoe running' },
  { emoji: '👗', tags: 'dress fashion clothing' },
  { emoji: '👜', tags: 'handbag purse fashion' },
  { emoji: '💎', tags: 'diamond gem luxury' },
  { emoji: '👑', tags: 'crown king queen' },
  { emoji: '🕶️', tags: 'sunglasses cool fashion' },
  { emoji: '⌚', tags: 'watch time luxury' },
  { emoji: '💍', tags: 'ring wedding jewelry' },
  { emoji: '🎩', tags: 'hat top formal' },
  { emoji: '👔', tags: 'tie business formal' },
  { emoji: '🛍️', tags: 'shopping bags retail' },
  { emoji: '💄', tags: 'lipstick makeup beauty' },
  // Tech
  { emoji: '💻', tags: 'laptop computer tech' },
  { emoji: '📱', tags: 'phone mobile tech' },
  { emoji: '🎮', tags: 'game controller gaming' },
  { emoji: '🎧', tags: 'headphones music audio' },
  { emoji: '📷', tags: 'camera photo picture' },
  { emoji: '🖥️', tags: 'desktop computer screen' },
  { emoji: '⌨️', tags: 'keyboard typing computer' },
  { emoji: '🔌', tags: 'plug electric power' },
  { emoji: '💾', tags: 'disk save storage' },
  { emoji: '🤖', tags: 'robot ai tech' },
  // Music & Art
  { emoji: '🎸', tags: 'guitar music rock' },
  { emoji: '🎹', tags: 'piano keyboard music' },
  { emoji: '🎨', tags: 'art paint palette' },
  { emoji: '🎭', tags: 'theater drama masks' },
  { emoji: '🎬', tags: 'movie film cinema' },
  { emoji: '🎤', tags: 'microphone singing karaoke' },
  { emoji: '🎵', tags: 'music note song' },
  { emoji: '📚', tags: 'books reading study' },
  { emoji: '✏️', tags: 'pencil write draw' },
  { emoji: '🖌️', tags: 'paintbrush art create' },
  // Sports
  { emoji: '⚽', tags: 'soccer football sport' },
  { emoji: '🏀', tags: 'basketball sport ball' },
  { emoji: '🎾', tags: 'tennis sport racket' },
  { emoji: '🏋️', tags: 'gym weights lifting' },
  { emoji: '🏄', tags: 'surfing wave beach' },
  { emoji: '🚴', tags: 'cycling bike sport' },
  { emoji: '⛷️', tags: 'skiing snow winter' },
  { emoji: '🏌️', tags: 'golf sport club' },
  { emoji: '🥊', tags: 'boxing sport fight' },
  { emoji: '🧘', tags: 'yoga meditation zen' },
  { emoji: '🏆', tags: 'trophy winner champion' },
  { emoji: '🥇', tags: 'medal gold first' },
  // Home
  { emoji: '🏠', tags: 'house home living' },
  { emoji: '🛋️', tags: 'couch sofa living' },
  { emoji: '🛏️', tags: 'bed sleep bedroom' },
  { emoji: '🪴', tags: 'plant green indoor' },
  { emoji: '🧹', tags: 'broom clean house' },
  { emoji: '🔑', tags: 'key lock house' },
  { emoji: '💡', tags: 'bulb light idea' },
  { emoji: '🪑', tags: 'chair seat furniture' },
  { emoji: '🖼️', tags: 'frame picture art' },
  { emoji: '🏡', tags: 'garden house home' },
  // Finance
  { emoji: '💰', tags: 'money bag rich' },
  { emoji: '💵', tags: 'dollar money cash' },
  { emoji: '💳', tags: 'card credit payment' },
  { emoji: '🏦', tags: 'bank finance building' },
  { emoji: '📈', tags: 'chart growth stock' },
  { emoji: '🐷', tags: 'pig piggybank savings' },
  { emoji: '💸', tags: 'money fly spending' },
  { emoji: '🪙', tags: 'coin money gold' },
  { emoji: '📊', tags: 'chart data stats' },
  { emoji: '🏧', tags: 'atm money bank' },
  // Celebration
  { emoji: '🎉', tags: 'party celebration confetti' },
  { emoji: '🎁', tags: 'gift present birthday' },
  { emoji: '🎂', tags: 'birthday cake candle' },
  { emoji: '🥂', tags: 'champagne toast cheers' },
  { emoji: '🎊', tags: 'confetti party celebrate' },
  { emoji: '⭐', tags: 'star favorite best' },
  { emoji: '🌟', tags: 'glow star shine' },
  { emoji: '🔥', tags: 'fire hot trending' },
  { emoji: '🎈', tags: 'balloon party fun' },
  { emoji: '🪩', tags: 'disco ball party' },
  // Animals
  { emoji: '🐶', tags: 'dog puppy pet' },
  { emoji: '🐱', tags: 'cat kitten pet' },
  { emoji: '🐴', tags: 'horse riding equestrian' },
  { emoji: '🐠', tags: 'fish aquarium tropical' },
  { emoji: '🦋', tags: 'butterfly insect nature' },
  { emoji: '🐦', tags: 'bird tweet nature' },
  { emoji: '🐢', tags: 'turtle slow nature' },
  { emoji: '🦁', tags: 'lion king safari' },
  { emoji: '🐼', tags: 'panda bear cute' },
  { emoji: '🦊', tags: 'fox clever animal' },
  // Nature
  { emoji: '🌸', tags: 'cherry blossom spring' },
  { emoji: '🌻', tags: 'sunflower yellow summer' },
  { emoji: '🌴', tags: 'palm tree tropical' },
  { emoji: '🍀', tags: 'clover lucky green' },
  { emoji: '🌈', tags: 'rainbow color sky' },
  { emoji: '☀️', tags: 'sun sunny weather' },
  { emoji: '🌙', tags: 'moon night sleep' },
  { emoji: '❄️', tags: 'snow winter cold' },
  { emoji: '🌊', tags: 'wave ocean sea' },
  { emoji: '🍂', tags: 'leaves autumn fall' },
  // Health
  { emoji: '💪', tags: 'muscle strong fitness' },
  { emoji: '🧠', tags: 'brain smart think' },
  { emoji: '❤️', tags: 'heart love health' },
  { emoji: '🩺', tags: 'stethoscope doctor medical' },
  { emoji: '💊', tags: 'pill medicine health' },
  { emoji: '🧬', tags: 'dna science genetics' },
  { emoji: '🦷', tags: 'tooth dental dentist' },
  { emoji: '👶', tags: 'baby child family' },
  { emoji: '🧘‍♀️', tags: 'meditation yoga calm' },
  { emoji: '🏥', tags: 'hospital medical health' },
  { emoji: '🩹', tags: 'bandaid heal care' },
  { emoji: '💆', tags: 'massage spa relax' },
];
